apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: homework
  name: homework-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: yc-network-hdd